### ISSUE TITLE
enauto4/m3/

### ISSUE THREAD

**Issue by zcrnivec** [nickrusso42518/enauto4#1]
Hi,

I am going through the sd-wan examples and I really like it so far! I have noticed one issue though, but I don't know if it is intentional or not.

In enauto4/m3 if you do apply that vsmart device template that is created within the code, then you will override all of the basic settings such as ip addresses ntp, etc. and in turn the vsmart will become unresponsive... After the 5 mins, the default rollback timer will kick in, and vsmart will become online again, but with the previous config.

I think the solution would be to create additional feature templates and add them to the device template. 

![image](https://user-images.githubusercontent.com/13747126/79837970-9a0a3900-83b2-11ea-813c-2c20ea8fa39e.png)

**Comment by nickrusso42518** [comment]
Hi, that's interesting, I hadn't observed that. I've already recorded and submitted the code, so I may need to issue a correction later. I don't believe there were any existing device templates, and I've always been able to reach the vSmart for long after applying the template. I'll test it again this morning.

**Comment by nickrusso42518** [comment]
OK, I think I may be seeing the issue, that's very weird. Even after the rollback, the device stays in vManage mode, which allows policies to be activated on it. I'll investigate this more later, as adding all these new feature templates is an enormous time sink and detour away from the course. Even with this error, it shouldn't detract from the lesson in general.

**Comment by nickrusso42518** [comment]
This is the danger of blindly using the factory default templates, as you said, because creating additional feature templates to customize the configuration for an individual environment is generally what you'd do. I went with the FD templates just to get things going, and I hope that real users would not use FD templates in their production environments! I'll add a note to the README in the meantime.

**Comment by nickrusso42518** [comment]
Commit 3047021

**Comment by zcrnivec** [comment]
I think that DevNet added some configuration manually to the devices, therefore it still works later on. What I did is that I copied the default template for Factory_Default_vSmart_vManage_VPN_0_Template and added interface template to it. But as you said it takes some time to do it through the GUI.

Thanks for the good work, and I am looking forward to see the video course!

**Comment by nickrusso42518** [comment]
Let's do this. Once my course publishes, please watch it, and using the "discovery" techniques I teach, can you help me come up with the real solution in a few weeks?

**Comment by zcrnivec** [comment]
I am definitely interested in that and looking forward to collaborate with you!

If you want we can continue this discussion on Webex Teams?

**Comment by nickrusso42518** [comment]
Yes, let's do that. Will close the issue and we can open a more technical one later.
